language: cpp
sudo: false

matrix:
  include:
    - os: linux
      compiler: gcc
      addons: *gcc49
      env: BUILD_TYPE='Release' C_COMPILER='gcc-4.9' CXX_COMPILER='g++-4.9'

    - os: linux
      compiler: clang
      addons: *clang38
      env: BUILD_TYPE='Release' C_COMPILER='clang-3.8' CXX_COMPILER='clang++-3.8'

    - os: osx
      osx_image: xcode8
      compiler: clang
      env: BUILD_TYPE='Release' C_COMPILER='clang' CXX_COMPILER='clang++'

before_install:
  - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake #https://github.com/travis-ci/travis-ci/issues/2212
  - sudo apt-get update
  - sudo apt-get install libfftw3-dev libopenmpi-dev libx11-dev zlib1g-dev libgsl0-dev libxml2-dev libblas-dev liblapack-dev libboost-dev cmake
  # Install gtest
  - wget https://github.com/google/googletest/archive/release-1.7.0.zip
  - unzip release-1.7.0.zip
  - cmake googletest-release-1.7.0
  - cmake --build googletest-release-1.7.0

script:
  - export GTEST_ROOT=${TRAVIS_BUILD_DIR}/googletest-release-1.7.0
  - mkdir build \
    && pushd build \
    && cmake .. \
         -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
         -DCMAKE_C_COMPILER=${C_COMPILER} \
         -DCMAKE_CXX_COMPILER=${CXX_COMPILER} \
         -DGMX_BUILD_MDRUN_ONLY=OFF \
         -DGMX_BUILD_FDA=ON \
         -DGMX_DEFAULT_SUFFIX=OFF \
         -DGMX_BINARY_SUFFIX=_fda \
         -DGMX_SIMD=NONE \
         -DGMX_BUILD_UNITTESTS=ON \
         -DGMX_BUILD_OWN_FFTW=ON \
         .. \
    && make -j4 \
    && make check

notifications:
  recipients:
    - bernd.doser@h-its.org
  email:
    on_success: change
    on_failure: always
