language: cpp
sudo: false

matrix:
  include:
    - os: linux
      compiler: gcc
      addons: &gcc49
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages:
            - g++-4.9
            - libfftw3-dev
            - libopenmpi-dev
            - libx11-dev
            - zlib1g-dev
            - libgsl0-dev
            - libxml2-dev
            - libblas-dev
            - liblapack-dev
            - libboost-graph-dev
      env: BUILD_TYPE='Release' C_COMPILER='gcc-4.9' CXX_COMPILER='g++-4.9'

    - os: linux
      compiler: gcc
      addons: *gcc49
      env: BUILD_TYPE='Debug' C_COMPILER='gcc-4.9' CXX_COMPILER='g++-4.9'

    - os: linux
      compiler: clang
      addons: &clang38
        apt:
          sources: ['llvm-toolchain-precise-3.8', 'ubuntu-toolchain-r-test']
          packages:
            - clang-3.8
            - libfftw3-dev
            - libopenmpi-dev
            - libx11-dev
            - zlib1g-dev
            - libgsl0-dev
            - libxml2-dev
            - libblas-dev
            - liblapack-dev
            - libboost-graph-dev
      env: BUILD_TYPE='Release' C_COMPILER='clang-3.8' CXX_COMPILER='clang++-3.8'

    - os: linux
      compiler: clang
      addons: *clang38
      env: BUILD_TYPE='Debug' C_COMPILER='clang-3.8' CXX_COMPILER='clang++-3.8'

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env: BUILD_TYPE='Release' C_COMPILER='clang' CXX_COMPILER='clang++'

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env: BUILD_TYPE='Debug' C_COMPILER='clang' CXX_COMPILER='clang++'

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.tar.gz"
      mkdir -p cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      GTEST_URL="https://github.com/google/googletest/archive/release-1.7.0.tar.gz"
      mkdir -p gtest && travis_retry wget --no-check-certificate --quiet -O - ${GTEST_URL} | tar --strip-components=1 -xz -C gtest
      cmake gtest
      cmake --build gtest
      export GTEST_ROOT=${DEPS_DIR}/gtest
    elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      which cmake || brew install cmake
    fi

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_C_COMPILER=${C_COMPILER} -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DGMX_BUILD_MDRUN_ONLY=OFF -DGMX_BUILD_FDA=ON -DGMX_DEFAULT_SUFFIX=OFF -DGMX_BINARY_SUFFIX=_fda -DGMX_SIMD=NONE -DGMX_BUILD_UNITTESTS=ON -DGMX_BUILD_OWN_FFTW=ON ..

script:
  - make -j 4
  - make check

notifications:
  recipients:
    - bernd.doser@h-its.org
  email:
    on_success: change
    on_failure: always
