FROM bernddoser/docker-devel-cpp:ubuntu-16.04-gcc-4.9-gtest-1.8.0-doxygen-1.8.5

MAINTAINER Bernd Doser <bernd.doser@h-its.org>

RUN apt-get update \
 && apt-get install -y \
    libboost-all-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
