FROM bernddoser/docker-devel-cpp:ubuntu-16.04-gcc-4.9-gtest-1.8.0

MAINTAINER Bernd Doser <bernd.doser@h-its.org>

RUN apt-get update \
 && apt-get install -y \
    libboost-graph-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
 
# Dummy doxygen binary to tell cmake it will be available
RUN touch /usr/bin/doxygen