FROM bernddoser/docker-devel-cpp:ubuntu-16.04-clang-4.0-gtest-1.8.0

MAINTAINER Bernd Doser <bernd.doser@h-its.org>

RUN apt-get update \
 && apt-get install -y \
    libboost-graph-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*