FROM braintwister/ubuntu-18.04-cmake-3.11-clang-6-gtest-1.8.0

MAINTAINER Bernd Doser <bernd.doser@h-its.org>

RUN apt-get update \
 && apt-get install -y \
    libboost-graph-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
