FROM braintwister/ubuntu-16.04-cmake-3.11-gcc-4.9-gtest-1.8.0-doxygen-1.8.13

MAINTAINER Bernd Doser <bernd.doser@h-its.org>

RUN apt-get update \
 && apt-get install -y \
    libboost-graph-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
